function r_A_E = ForwardKin(l1,l2,l3,th1,th2,th3)
%FORWARDKIN
%    R_A_E = FORWARDKIN(L1,L2,L3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Jan-2021 14:58:16

t2 = conj(th1);
t3 = conj(th2);
t4 = conj(th3);
t5 = t2+t3;
t6 = t4+t5;
r_A_E = [l1.*cos(t2)+l2.*cos(t5)+l3.*cos(t6);l1.*sin(t2)+l2.*sin(t5)+l3.*sin(t6);0.0];
