function C = getC(t,l1,l2,m2,theta_1,theta_2,w1,w2)
%GETC
%    C = GETC(T,L1,L2,M2,THETA_1,THETA_2,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Aug-2021 15:19:30

t2 = sin(theta_2);
t3 = l2.^2;
t4 = theta_1.*2.0;
t5 = w1.^2;
t6 = w2.^2;
t7 = sin(t4);
t8 = t4+theta_2;
t9 = sin(t8);
C = [m2.*(l1.^2.*t5.*t7.*-2.0+t2.*t3.*t6+t3.*t5.*t7.*2.0+t3.*t5.*t9.*2.0+t3.*t6.*t9+l1.*l2.*t2.*t6-l1.*l2.*t5.*t9.*2.0-l1.*l2.*t6.*t9+t2.*t3.*w1.*w2.*2.0+t3.*t9.*w1.*w2.*2.0+l1.*l2.*t2.*w1.*w2.*2.0-l1.*l2.*t9.*w1.*w2.*2.0).*(-1.0./4.0);(l2.*m2.*t5.*(l1.*t2+l2.*t2+l1.*t9-l2.*t9))./4.0];
