function G = getG(t,g,l1,l2,m1,m2,theta_1,theta_2)
%GETG
%    G = GETG(T,G,L1,L2,M1,M2,THETA_1,THETA_2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Aug-2021 15:19:30

t2 = cos(theta_1);
t3 = theta_1+theta_2;
t4 = cos(t3);
G = [g.*((l1.*m1.*t2)./2.0+l1.*m2.*t2+(l2.*m2.*t4)./2.0);(g.*l2.*m2.*t4)./2.0];
