function H = getH(t,l1,l2,m1,m2,theta_1,theta_2)
%GETH
%    H = GETH(T,L1,L2,M1,M2,THETA_1,THETA_2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Aug-2021 15:19:30

t2 = cos(theta_2);
t3 = l2.*4.0;
t4 = l1.^2;
t5 = l2.^2;
t6 = theta_1.*2.0;
t7 = cos(t6);
t8 = l1.*t2.*3.0;
t9 = l2.*t2.*3.0;
t10 = t6+theta_2;
t11 = cos(t10);
t12 = l1.*t11.*3.0;
t13 = l2.*t11.*3.0;
t14 = -t12;
t15 = t3+t8+t9+t13+t14;
t16 = (l2.*m2.*t15)./1.2e+1;
H = reshape([(m1.*t4)./3.0+(m2.*t4)./2.0+m2.*t5.*(5.0./6.0)+(m2.*t2.*t5)./2.0-(m2.*t4.*t7)./2.0+(m2.*t5.*t7)./2.0+(m2.*t5.*t11)./2.0+(l1.*l2.*m2.*t2)./2.0-(l1.*l2.*m2.*t11)./2.0,t16,t16,(m2.*t5)./3.0],[2,2]);
